import { Customer, CustomerFormData } from '@/types/customer';
import { supabase } from '@/integrations/supabase/client';

/**
 * Save a new customer to Supabase database
 */
export const saveCustomer = async (formData: CustomerFormData): Promise<Customer> => {
    const { data, error } = await supabase
        .from('customers')
        .insert({
            full_name: formData.fullName,
            phone: formData.phone,
            age: parseInt(formData.age),
            gender: formData.gender,
            address: formData.address,
            emergency_contact: formData.emergencyContact,
            membership_type: formData.membershipType,
            start_date: formData.startDate,
            customer_id: '', // Will be auto-generated by trigger
        })
        .select()
        .single();

    if (error) {
        console.error('Error saving customer:', error);
        throw new Error('Failed to save customer: ' + error.message);
    }

    if (!data) {
        throw new Error('No data returned from insert');
    }

    // Convert database format to Customer type
    return {
        id: data.id,
        customerId: data.customer_id,
        fullName: data.full_name,
        phone: data.phone,
        age: data.age.toString(),
        gender: data.gender as 'male' | 'female' | 'other',
        address: data.address,
        emergencyContact: data.emergency_contact,
        membershipType: data.membership_type as any,
        startDate: data.start_date,
        createdAt: data.created_at,
    };
};

/**
 * Get all customers from Supabase database
 */
export const getAllCustomers = async (): Promise<Customer[]> => {
    const { data, error } = await supabase
        .from('customers')
        .select('*')
        .order('created_at', { ascending: false });

    if (error) {
        console.error('Error fetching customers:', error);
        throw new Error('Failed to fetch customers: ' + error.message);
    }

    // Convert database format to Customer type
    return (data || []).map(item => ({
        id: item.id,
        customerId: item.customer_id,
        fullName: item.full_name,
        phone: item.phone,
        age: item.age.toString(),
        gender: item.gender as 'male' | 'female' | 'other',
        address: item.address,
        emergencyContact: item.emergency_contact,
        membershipType: item.membership_type as any,
        startDate: item.start_date,
        createdAt: item.created_at,
    }));
};

/**
 * Get a single customer by ID
 */
export const getCustomerById = async (customerId: string): Promise<Customer | null> => {
    const { data, error } = await supabase
        .from('customers')
        .select('*')
        .eq('customer_id', customerId)
        .single();

    if (error) {
        console.error('Error fetching customer:', error);
        return null;
    }

    if (!data) return null;

    return {
        id: data.id,
        customerId: data.customer_id,
        fullName: data.full_name,
        phone: data.phone,
        age: data.age.toString(),
        gender: data.gender as 'male' | 'female' | 'other',
        address: data.address,
        emergencyContact: data.emergency_contact,
        membershipType: data.membership_type as any,
        startDate: data.start_date,
        createdAt: data.created_at,
    };
};

/**
 * Export customers as CSV string
 */
export const exportCustomersAsCSV = (customers: Customer[]): string => {
    if (customers.length === 0) return '';

    const headers = [
        'Customer ID',
        'Full Name',
        'Phone',
        'Age',
        'Gender',
        'Address',
        'Emergency Contact',
        'Membership Type',
        'Start Date',
        'Created At',
    ];

    const rows = customers.map(c => [
        c.customerId,
        c.fullName,
        c.phone,
        c.age,
        c.gender,
        c.address,
        c.emergencyContact,
        c.membershipType,
        c.startDate,
        c.createdAt,
    ]);

    const csvContent = [
        headers.join(','),
        ...rows.map(row => row.map(cell => `"${cell}"`).join(',')),
    ].join('\n');

    return csvContent;
};

/**
 * Subscribe to real-time customer updates
 */
export const subscribeToCustomers = (callback: (customers: Customer[]) => void) => {
    const channel = supabase
        .channel('customers_changes')
        .on(
            'postgres_changes',
            {
                event: '*',
                schema: 'public',
                table: 'customers',
            },
            async () => {
                // Fetch updated customer list
                const customers = await getAllCustomers();
                callback(customers);
            }
        )
        .subscribe();

    return () => {
        supabase.removeChannel(channel);
    };
};
